const bn = (b)=>b.reduce((p, t,i)=>p+t*Math.pow(2, i));
const nb = (n, l)=>new Array(l).fill(0).reduce((p, t, i)=>p.concat([(n&Math.pow(2, i))===0?0:1]), []);
const bybi = (b)=>b.reduce((p, t)=>p.concat(nb(t, 8)), []);
const biby = (b)=>new Array(Math.ceil(b.length/8)).fill(0).reduce((p, t, i)=>p.concat(bn(b.slice(i*8, i*8+8))), []);

const es = (s, c, l)=>s.split("").reduce((p, v)=>p.concat(nb(c.indexOf(v), l)), []);
const ds = (b, c, l)=>new Array(Math.ceil(b.length/l)).fill(0).reduce((p, t, i)=>p+c[bn(b.slice(i*l, i*l+l))], "");

const bs = (b)=>b.map(v=>String.fromCharCode(v)).join("");
const sb = (s)=>s.split("").map((v,i)=>s.charCodeAt(i));

const at = "animation,animation-delay,animation-direction,animation-duration,animation-fill-mode,animation-iteration-count,animation-name,animation-play-state,animation-timing-function,backface-visibility,background,background-attachment,background-clip,background-color,background-image,background-origin,background-position,background-position-x,background-position-y,background-repeat,background-size,border,border-style,border-width,border-color,border-bottom,border-bottom-color,border-bottom-left-radius,border-bottom-right-radius,border-bottom-style,border-bottom-width,border-collapse,border-image,border-left,border-left-color,border-left-style,border-left-width,border-radius,border-right,border-right-color,border-right-style,border-right-width,border-spacing,border-top,border-top-color,border-top-left-radius,border-top-right-radius,border-top-style,border-top-width,bottom,box-shadow,box-sizing,caption-side,clear,clip,color,columns,column-count,column-fill,column-gap,column-rule,column-rule-color,column-rule-style,column-rule-width,column-span,column-width,content,counter-increment,counter-reset,cursor,direction,display,empty-cells,float,font,font-family,font-size,font-style,font-variant,font-weight,height,hyphens,left,letter-spacing,line-height,list-style,list-style-image,list-style-position,list-style-type,margin,margin-bottom,margin-left,margin-right,margin-top,max-height,max-width,min-height,min-width,opacity,orphans,outline,outline-color,outline-style,outline-width,overflow,overflow-x,overflow-y,padding,padding-bottom,padding-left,padding-right,padding-top,page-break-after,page-break-before,page-break-inside,perspective,perspective-origin,position,quotes,right,tab-size,table-layout,text-align,text-align-last,text-decoration,text-decoration-color,text-decoration-line,text-decoration-style,text-indent,text-shadow,text-transform,top,transform,transform-style,transition,transition-delay,transition-duration,transition-property,transition-timing-function,unicode-bidi,vertical-align,visibility,white-space,widows,width,word-spacing,z-index,flex-direction,resize,scrollbar-width".split(",");
const wd = "solid,dashed,dotted,0,black,gray,white,blue,yellow,transparent,none,border-box,scroll,hidden,visible,flex,center,block".split(",");
const sc = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-,:=[]*\"#?>.".split("");
const vc = "abcdefghijklmnopqrstuvwxyz0123456789+%-()*\"#?>.:/ ".split("");
const e = {"%": 7, "px": 11, "vw": 7, "vh": 7, "s": 7, "ms": 12};